### ISSUE TITLE
Match version in build script

### ISSUE THREAD

**Issue by dblock** [opensearch-project/job-scheduler#32]
The version in https://github.com/opensearch-project/job-scheduler/blob/main/.github/workflows/test-and-build-workflow.yml#L42 and similar should be `rc1` right now, just so someone doesn't accidentally copy-paste the wrong version. Like here: https://github.com/opensearch-project/common-utils/blob/main/.github/workflows/ci.yml#L37

**Comment by dblock** [comment]
@tlfeng maybe take this?

**Comment by tlfeng** [comment]
Hi dB, it's very kind of you to provide an correct example. 😄

I will add `-Dbuild.version_qualifier=rc1` in the parameter of building OpenSearch:
https://github.com/opensearch-project/job-scheduler/blob/67ec362748e298dd24249a7c03759ec5a010234c/.github/workflows/test-and-build-workflow.yml#L37
In addition, I also plan to remove the version parameter of building Job Scheduler plugin:
https://github.com/opensearch-project/job-scheduler/blob/67ec362748e298dd24249a7c03759ec5a010234c/.github/workflows/test-and-build-workflow.yml#L42
because the version property has been declared in the build script:
https://github.com/opensearch-project/job-scheduler/blob/67ec362748e298dd24249a7c03759ec5a010234c/build.gradle#L29
